@inventory_service_HostAddress = http://localhost:5277

GET {{inventory_service_HostAddress}}/api/products
Accept: application/json

###

POST {{inventory_service_HostAddress}}/api/products
Content-Type: application/json

{
  "code": "PROD-001",
  "description": "Produto de demonstração",
  "stockQuantity": 10
}

###

POST {{inventory_service_HostAddress}}/api/products/decrease-stock
Content-Type: application/json

{
  "idempotencyKey": "manual-test-001",
  "items": [
    {
      "productId": 1,
      "quantity": 2
    }
  ]
}
